[data]
films_csv = "data/films.csv"
ratings_tsv = "data/title.ratings.tsv"
main_universe_parquet = "data/main_universe_extracted.parquet"
extracted_parquet = "data/films_extracted.parquet"
transformed_parquet = "data/films_transformed.parquet"

[output]
recommendations_csv = "output/recommendations.csv"
primary_language_recommendations_csv = "output/primary_language_recommendations.csv"
foreign_language_recommendations_csv = "output/foreign_language_recommendations.csv"

[user]
primary_language = 'English' # Title case